<?xml version="1.0" encoding="utf-8"?><Database Name="PlaygroundDB" Class="CandidatesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=PlaygroundDB;Integrated Security=True" SettingsObjectName="Candidate.Data.Properties.Settings" SettingsPropertyName="PlaygroundDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Candidates" Member="Applicants">
    <Type Name="Applicant">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="true" />
      <Column Name="Status" Type="Status" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>